### ISSUE TITLE
Setup Kanban Board 🪄

### ISSUE THREAD

**Issue by ritikarawat220** [ritikarawat220/Recipe-App#16]
We are 3 on this team @ritikarawat220 #1, @jeanbuhendwa #2 and  @cherelemma  #3:

- Here is a link to the [Kanban board](https://github.com/ritikarawat220/Recipe-App/projects/1)
- Here is a link to the [repo](https://github.com/ritikarawat220/Recipe-App)

**Comment by Abenezer-Tilahun** [comment]
Hi @ritikarawat220 @jeanbuhendwa @cherelemma 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ Good job for Provide the information about the number of people in their group.
✔️ Good Job for Provide link to their GitHub project.
✔️ Good Job for Implementing RoR group project: set up your Kanban board .
## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
